# NAME: Justin Hong
# EMAIL: justinjh@ucla.edu
# ID: 604565186

default:
	gcc -g -o lab1a lab1a.c
clean:
	rm -f lab1a lab1a-604565186.tar.gz
sources = Makefile README lab1a.c
dist:
	tar -czvf lab1a-604565186.tar.gz $(sources) 